### ISSUE TITLE
milk contains fat

### ISSUE THREAD

**Issue by crabdancing** [emilyploszaj/nourish#1]
It's like mostly fat. Milk should give some significant fat by default.

**Comment by emilyploszaj** [comment]
currently milk, while tagged as protein, does not actually give any nutrients because it does not provide any hunger. it is hard to balance a nutrient if you can get a bunch of it for free with nothing preventing maxing it out. a lot of the balancing of nourish actually relies on the fact that you cannot eat while you are hungry. nutrients are also provided proportional to the hunger and saturation they restore. because of these reasons I'm not sure how to approach adding nutrients to consumables that don't provide hunger

**Comment by crabdancing** [comment]
Maybe add a diminishing returns system so that you get less and less nutrition from drinks?
